# Generated by Django 5.1.4 on 2026-08-20 16:42

import apps.accounts.managers
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='телефон')),
                ('code_hash', models.CharField(max_length=128, verbose_name='хеш кода')),
                ('expires_at', models.DateTimeField(verbose_name='действителен до')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='использован')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='попыток ввода')),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP запроса')),
            ],
            options={
                'verbose_name': 'SMS-код',
                'verbose_name_plural': 'SMS-коды',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', '-created_at'], name='accounts_ot_phone_c9778d_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='телефон')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='имя')),
                ('role', models.CharField(choices=[('client', 'Клиент'), ('master', 'Мастер'), ('admin', 'Администратор')], default='client', max_length=16, verbose_name='роль')),
                ('car_model', models.CharField(blank=True, max_length=120, verbose_name='марка и модель')),
                ('car_plate', models.CharField(blank=True, max_length=16, verbose_name='госномер')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('is_staff', models.BooleanField(default=False, verbose_name='доступ в админку')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата регистрации')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('service_points', models.ManyToManyField(blank=True, help_text='Пусто = доступ ко всем точкам', related_name='masters', to='catalog.servicepoint', verbose_name='точки мастера')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'indexes': [models.Index(fields=['role', 'is_active'], name='accounts_us_role_2b136f_idx')],
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
    ]
