# Generated by Django 5.2.17 on 2026-09-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="otpcode",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "код входа",
                "verbose_name_plural": "коды входа",
            },
        ),
        migrations.AddField(
            model_name="otpcode",
            name="channel",
            field=models.CharField(
                choices=[("call", "Звонок"), ("sms", "SMS")],
                default="sms",
                max_length=8,
                verbose_name="канал",
            ),
        ),
    ]
