# Generated by Django 5.2.17 on 2026-09-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_otpcode_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="otpcode",
            name="provider_request_id",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="id у шлюза"
            ),
        ),
        migrations.AddField(
            model_name="otpcode",
            name="session_hash",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="хеш сессии"
            ),
        ),
        migrations.AlterField(
            model_name="otpcode",
            name="channel",
            field=models.CharField(
                choices=[
                    ("call", "Звонок"),
                    ("reverse_call", "Обратный звонок"),
                    ("sms", "SMS"),
                ],
                default="sms",
                max_length=16,
                verbose_name="канал",
            ),
        ),
    ]
