# Generated by Django 5.2.18 on 2026-10-06 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_otp_verificahub"),
        # Сначала машина переезжает в гараж, потом поля исчезают.
        ("garage", "0002_cars_from_user_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="car_model",
        ),
        migrations.RemoveField(
            model_name="user",
            name="car_plate",
        ),
    ]
