line-length = 100
target-version = "py312"

exclude = ["migrations"]

[lint]
select = ["E", "F", "I", "UP", "B", "DJ", "C4", "SIM"]
ignore = ["B008", "DJ001"]

[lint.isort]
known-first-party = ["apps", "config"]
