# Generated by Django 5.2.18 on 2026-10-06 18:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0003_service_point_timezone_workdays"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="марка и модель"
                    ),
                ),
                (
                    "plate",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="госномер"
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="год выпуска"
                    ),
                ),
                (
                    "mileage",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="пробег, км"
                    ),
                ),
                (
                    "vin",
                    models.CharField(blank=True, max_length=17, verbose_name="VIN"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="основной"),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="удалён клиентом"
                    ),
                ),
                (
                    "make",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.carmake",
                        verbose_name="марка из справочника",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.carmodel",
                        verbose_name="модель из справочника",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "автомобиль клиента",
                "verbose_name_plural": "автомобили клиентов",
                "ordering": ["-is_primary", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "archived_at"],
                        name="garage_car_user_id_a19663_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("archived_at__isnull", True), ("is_primary", True)
                        ),
                        fields=("user",),
                        name="uniq_primary_car_per_user",
                    )
                ],
            },
        ),
    ]
