# Generated by Django 5.2.18 on 2026-10-07 11:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garage", "0002_cars_from_user_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="inspection_until",
            field=models.DateField(
                blank=True, null=True, verbose_name="техосмотр действует до"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="oil_interval_km",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="масло: интервал, км"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="oil_interval_months",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="масло: интервал, месяцев"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="osago_until",
            field=models.DateField(
                blank=True, null=True, verbose_name="ОСАГО действует до"
            ),
        ),
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("fuel", "Заправка"),
                            ("oil", "Замена масла"),
                            ("service", "ТО и ремонт"),
                            ("tires", "Шиномонтаж"),
                            ("wash", "Мойка"),
                            ("fine", "Штраф"),
                            ("other", "Другое"),
                        ],
                        max_length=16,
                        verbose_name="что",
                    ),
                ),
                ("date", models.DateField(verbose_name="когда")),
                (
                    "mileage",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="пробег, км"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="сумма, ₽",
                    ),
                ),
                (
                    "liters",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="литры",
                    ),
                ),
                (
                    "full_tank",
                    models.BooleanField(default=True, verbose_name="полный бак"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="заметка"
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="garage.car",
                        verbose_name="автомобиль",
                    ),
                ),
            ],
            options={
                "verbose_name": "запись дневника",
                "verbose_name_plural": "дневник водителя",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["car", "kind", "-date"],
                        name="garage_loge_car_id_d6aeb8_idx",
                    )
                ],
            },
        ),
    ]
