# Generated by Django 5.1.15 on 2026-09-19 19:13

import apps.referral.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("booking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralNode",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=apps.referral.models.generate_referral_code,
                        max_length=8,
                        unique=True,
                        verbose_name="код приглашения",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        choices=[("left", "левое"), ("right", "правое")],
                        max_length=5,
                        verbose_name="место под родителем",
                    ),
                ),
                (
                    "depth",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="уровень в матрице"
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="баллы"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="referral.referralnode",
                        verbose_name="над ним в матрице",
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invited",
                        to="referral.referralnode",
                        verbose_name="пригласил",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_node",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "участник программы",
                "verbose_name_plural": "участники программы",
                "ordering": ("depth", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="PointsEntry",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="баллы"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("accrual", "начисление"),
                            ("spend", "списание"),
                            ("adjustment", "корректировка"),
                        ],
                        max_length=12,
                        verbose_name="тип",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="линия"
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="ставка, %",
                    ),
                ),
                (
                    "base_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="база начисления",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="комментарий"
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="points_entries",
                        to="booking.booking",
                        verbose_name="запись",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="referral.referralnode",
                        verbose_name="кому",
                    ),
                ),
                (
                    "source_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_entries",
                        to="referral.referralnode",
                        verbose_name="с чьего чека",
                    ),
                ),
            ],
            options={
                "verbose_name": "движение баллов",
                "verbose_name_plural": "движения баллов",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="referralnode",
            index=models.Index(
                fields=["parent", "position"], name="referral_re_parent__e9e8d6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="referralnode",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", False)),
                fields=("parent", "position"),
                name="uniq_matrix_slot",
            ),
        ),
        migrations.AddIndex(
            model_name="pointsentry",
            index=models.Index(
                fields=["node", "-created_at"], name="referral_po_node_id_257e28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pointsentry",
            index=models.Index(
                fields=["kind", "-created_at"], name="referral_po_kind_8117ee_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="pointsentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "accrual")),
                fields=("booking", "node"),
                name="uniq_accrual_per_booking_node",
            ),
        ),
    ]
