# Generated by Django 5.2.17 on 2026-09-23 19:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_booking_points_spent"),
        ("referral", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="referralnode",
            name="carry_left",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="перенос левого плеча",
            ),
        ),
        migrations.AddField(
            model_name="referralnode",
            name="carry_right",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="перенос правого плеча",
            ),
        ),
        migrations.AlterField(
            model_name="pointsentry",
            name="kind",
            field=models.CharField(
                choices=[
                    ("accrual", "начисление"),
                    ("payout", "выплата"),
                    ("spend", "списание"),
                    ("adjustment", "корректировка"),
                ],
                max_length=12,
                verbose_name="тип",
            ),
        ),
        migrations.CreateModel(
            name="BinarySettlement",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("day", models.DateField(verbose_name="сутки (по времени выплат)")),
                (
                    "left_before",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="перенос слева"
                    ),
                ),
                (
                    "right_before",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="перенос справа"
                    ),
                ),
                (
                    "left_added",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="пришло слева"
                    ),
                ),
                (
                    "right_added",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="пришло справа"
                    ),
                ),
                (
                    "paid",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="выплачено"
                    ),
                ),
                (
                    "left_after",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="осталось слева"
                    ),
                ),
                (
                    "right_after",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="осталось справа"
                    ),
                ),
                (
                    "entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settlement",
                        to="referral.pointsentry",
                        verbose_name="строка журнала",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlements",
                        to="referral.referralnode",
                        verbose_name="участник",
                    ),
                ),
            ],
            options={
                "verbose_name": "сведение плеч",
                "verbose_name_plural": "сведения плеч",
                "ordering": ("-day",),
            },
        ),
        migrations.CreateModel(
            name="LegCredit",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("left", "левое"), ("right", "правое")],
                        max_length=5,
                        verbose_name="плечо",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="баллы"
                    ),
                ),
                ("level", models.PositiveSmallIntegerField(verbose_name="линия")),
                (
                    "percent",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="ставка, %"
                    ),
                ),
                (
                    "base_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="база"
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leg_credits",
                        to="booking.booking",
                        verbose_name="запись",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leg_credits",
                        to="referral.referralnode",
                        verbose_name="кому в плечо",
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credits",
                        to="referral.binarysettlement",
                        verbose_name="сведено",
                    ),
                ),
                (
                    "source_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_credits",
                        to="referral.referralnode",
                        verbose_name="с чьего чека",
                    ),
                ),
            ],
            options={
                "verbose_name": "баллы в плечо",
                "verbose_name_plural": "баллы в плечи",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="binarysettlement",
            constraint=models.UniqueConstraint(
                fields=("node", "day"), name="uniq_settlement_per_day"
            ),
        ),
        migrations.AddIndex(
            model_name="legcredit",
            index=models.Index(
                fields=["settlement", "created_at"],
                name="referral_le_settlem_690baa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="legcredit",
            index=models.Index(
                fields=["node", "settlement"], name="referral_le_node_id_787d8c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="legcredit",
            constraint=models.UniqueConstraint(
                fields=("booking", "node"), name="uniq_credit_per_booking_node"
            ),
        ),
    ]
