# Generated by Django 5.1.4 on 2026-08-20 16:42

import apps.booking.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=apps.booking.models.generate_booking_code, max_length=8, unique=True, verbose_name='код записи')),
                ('start_at', models.DateTimeField(db_index=True, verbose_name='начало')),
                ('end_at', models.DateTimeField(verbose_name='окончание')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('completed', 'Выполнена'), ('cancelled_by_client', 'Отменена клиентом'), ('cancelled_by_master', 'Отменена сервисом'), ('no_show', 'Клиент не приехал')], db_index=True, default='pending', max_length=24, verbose_name='статус')),
                ('client_name', models.CharField(blank=True, max_length=150, verbose_name='имя клиента')),
                ('client_phone', models.CharField(max_length=20, verbose_name='телефон клиента')),
                ('car_model', models.CharField(blank=True, max_length=120, verbose_name='автомобиль')),
                ('car_plate', models.CharField(blank=True, max_length=16, verbose_name='госномер')),
                ('oil_title', models.CharField(max_length=255, verbose_name='масло (снимок)')),
                ('oil_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена масла')),
                ('work_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена работ')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='итого')),
                ('client_comment', models.CharField(blank=True, max_length=500, verbose_name='комментарий клиента')),
                ('cancel_reason', models.CharField(blank=True, max_length=500, verbose_name='причина отмены')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='отменена')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='напоминание отправлено')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL, verbose_name='кто отменил')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='served_bookings', to=settings.AUTH_USER_MODEL, verbose_name='мастер')),
                ('oil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.oil', verbose_name='масло')),
                ('service_point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.servicepoint', verbose_name='точка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'записи',
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingDraft',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step', models.CharField(choices=[('started', 'Начата'), ('point_selected', 'Выбран адрес'), ('oil_selected', 'Выбрано масло'), ('slot_selected', 'Выбрано время'), ('confirmed', 'Подтверждена'), ('expired', 'Истекла'), ('cancelled', 'Отменена клиентом')], default='started', max_length=20, verbose_name='шаг')),
                ('is_open', models.BooleanField(default=True, verbose_name='активен')),
                ('close_reason', models.CharField(blank=True, choices=[('confirmed', 'Запись подтверждена'), ('expired', 'Истекло время'), ('cancelled', 'Отменена клиентом'), ('restarted', 'Начата заново')], max_length=20, verbose_name='причина закрытия')),
                ('slot_start', models.DateTimeField(blank=True, null=True, verbose_name='начало слота')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='истекает')),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft', to='booking.booking', verbose_name='итоговая запись')),
                ('oil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='catalog.oil', verbose_name='масло')),
                ('service_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='catalog.servicepoint', verbose_name='точка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_drafts', to=settings.AUTH_USER_MODEL, verbose_name='клиент')),
            ],
            options={
                'verbose_name': 'черновик записи',
                'verbose_name_plural': 'черновики записей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingStatusLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=24, verbose_name='из статуса')),
                ('to_status', models.CharField(max_length=24, verbose_name='в статус')),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='комментарий')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='кто изменил')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='booking.booking', verbose_name='запись')),
            ],
            options={
                'verbose_name': 'смена статуса',
                'verbose_name_plural': 'история статусов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['service_point', 'start_at', 'status'], name='booking_boo_service_a003c7_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', '-start_at'], name='booking_boo_user_id_90e79b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'start_at'], name='booking_boo_status_bcac9d_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['in_progress', 'pending'])), fields=('user', 'start_at'), name='uniq_active_booking_per_user_slot'),
        ),
        migrations.AddIndex(
            model_name='bookingdraft',
            index=models.Index(fields=['service_point', 'slot_start', 'is_open'], name='booking_boo_service_c95228_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingdraft',
            index=models.Index(fields=['is_open', 'expires_at'], name='booking_boo_is_open_d69526_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookingdraft',
            constraint=models.UniqueConstraint(condition=models.Q(('is_open', True)), fields=('user',), name='uniq_open_draft_per_user'),
        ),
    ]
