# Generated by Django 5.2.17 on 2026-09-27 18:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_booking_points_spent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="final_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="итог при расчёте",
            ),
        ),
        migrations.CreateModel(
            name="BookingPriceChange",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменено"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "old_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="было"
                    ),
                ),
                (
                    "new_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="стало"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="причина"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_price_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кто изменил",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_changes",
                        to="booking.booking",
                        verbose_name="запись",
                    ),
                ),
            ],
            options={
                "verbose_name": "изменение итога",
                "verbose_name_plural": "изменения итога",
                "ordering": ["-created_at"],
            },
        ),
    ]
