# Generated by Django 5.2.18 on 2026-10-06 18:45

import re

import django.db.models.deletion
from django.db import migrations, models

_LAT = "ABEKMHOPCTYX"
_CYR = "АВЕКМНОРСТУХ"


def _plate(raw: str) -> str:
    """Та же форма номера, что в garage.0002."""
    value = re.sub(r"[\s\-]", "", raw or "").upper()
    letters = {ch for ch in value if ch.isalpha()}
    if letters and letters <= set(_LAT + _CYR):
        value = value.translate(str.maketrans(_LAT, _CYR))
    return value[:16]


def link_bookings(apps, schema_editor):
    """Старые записи — к машине, перенесённой из профиля.

    Только если снимок в записи совпадает с этой машиной: клиент мог
    сменить машину в профиле, и запись двухлетней давности на другую
    машину осталась бы привязанной к нынешней. Несовпавшие остаются без
    ссылки — их машина видна из снимка, как и раньше.
    """
    Booking = apps.get_model("booking", "Booking")
    Car = apps.get_model("garage", "Car")

    for car in Car.objects.filter(archived_at__isnull=True).iterator():
        title = " ".join(car.title.split()).lower()
        ids = [
            pk
            for pk, model, plate in Booking.objects.filter(user_id=car.user_id, car__isnull=True)
            .values_list("pk", "car_model", "car_plate")
            if " ".join((model or "").split()).lower() == title and _plate(plate) == car.plate
        ]
        if ids:
            Booking.objects.filter(pk__in=ids).update(car=car)


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_final_price"),
        ("garage", "0002_cars_from_user_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="garage.car",
                verbose_name="автомобиль",
            ),
        ),
        migrations.RunPython(link_bookings, migrations.RunPython.noop),
    ]
