# Generated by Django 5.1.4 on 2026-08-20 16:42

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePoint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='название')),
                ('address', models.CharField(max_length=255, verbose_name='адрес')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='телефон')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='долгота')),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=64, verbose_name='часовой пояс')),
                ('opens_at', models.TimeField(default=datetime.time(9, 0), verbose_name='открытие')),
                ('closes_at', models.TimeField(default=datetime.time(21, 0), verbose_name='закрытие')),
                ('workdays', models.JSONField(default=list, help_text='Дни недели, 0 = понедельник. Пустой список = работает всегда.', verbose_name='рабочие дни')),
                ('slot_minutes', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5)], verbose_name='длительность слота, мин')),
                ('posts_count', models.PositiveSmallIntegerField(default=2, help_text='Сколько машин обслуживается одновременно — ёмкость одного слота.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='постов')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
            ],
            options={
                'verbose_name': 'точка обслуживания',
                'verbose_name_plural': 'точки обслуживания',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Oil',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=80, verbose_name='бренд')),
                ('name', models.CharField(max_length=120, verbose_name='название')),
                ('viscosity', models.CharField(help_text='Например, 5W-30', max_length=16, verbose_name='вязкость')),
                ('oil_type', models.CharField(choices=[('synthetic', 'Синтетическое'), ('semi_synthetic', 'Полусинтетическое'), ('mineral', 'Минеральное')], default='synthetic', max_length=20, verbose_name='тип')),
                ('volume_liters', models.DecimalField(decimal_places=1, default=4, max_digits=4, verbose_name='объём канистры, л')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена за канистру, ₽')),
                ('work_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='стоимость работ, ₽')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='в продаже')),
            ],
            options={
                'verbose_name': 'масло',
                'verbose_name_plural': 'масла',
                'ordering': ['brand', 'name'],
                'constraints': [models.UniqueConstraint(fields=('brand', 'name', 'viscosity', 'volume_liters'), name='uniq_oil_sku')],
            },
        ),
        migrations.CreateModel(
            name='OilStock',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='остаток, канистр')),
                ('oil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='catalog.oil', verbose_name='масло')),
                ('service_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='catalog.servicepoint', verbose_name='точка')),
            ],
            options={
                'verbose_name': 'остаток масла',
                'verbose_name_plural': 'остатки масла',
                'indexes': [models.Index(fields=['service_point', 'oil'], name='catalog_oil_service_d9acd8_idx')],
                'constraints': [models.UniqueConstraint(fields=('service_point', 'oil'), name='uniq_stock_per_point')],
            },
        ),
    ]
