# Generated by Django 5.1.4 on 2026-09-21 21:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='марка')),
                ('search_terms', models.CharField(blank=True, help_text='Через запятую: мерс, мерседес, merc', max_length=255, verbose_name='синонимы для поиска')),
                ('search_index', models.CharField(blank=True, db_index=True, editable=False, max_length=512, verbose_name='поисковая форма')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='порядок в списке')),
                ('is_active', models.BooleanField(default=True, verbose_name='показывать')),
            ],
            options={
                'verbose_name': 'марка автомобиля',
                'verbose_name_plural': 'марки автомобилей',
                'ordering': ('sort_order', 'name'),
                'indexes': [models.Index(fields=['is_active', 'sort_order', 'name'], name='catalog_car_is_acti_fca314_idx')],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='модель')),
                ('search_terms', models.CharField(blank=True, max_length=255, verbose_name='синонимы для поиска')),
                ('search_index', models.CharField(blank=True, db_index=True, editable=False, max_length=512, verbose_name='поисковая форма')),
                ('is_active', models.BooleanField(default=True, verbose_name='показывать')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='catalog.carmake', verbose_name='марка')),
            ],
            options={
                'verbose_name': 'модель автомобиля',
                'verbose_name_plural': 'модели автомобилей',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['make', 'is_active', 'name'], name='catalog_car_make_id_1a6869_idx')],
                'constraints': [models.UniqueConstraint(fields=('make', 'name'), name='uniq_model_per_make')],
            },
        ),
    ]
