import zoneinfo

# Generated by Django 5.2.17 on 2026-09-24 14:54

import apps.catalog.models
from django.db import migrations, models


# Копия правил из catalog.models.normalize_timezone на момент миграции:
# миграция должна давать тот же результат и после правок модели.
ALIASES = {
    "yekaterinburg": "Asia/Yekaterinburg",
    "екатеринбург": "Asia/Yekaterinburg",
    "chelyabinsk": "Asia/Yekaterinburg",
    "челябинск": "Asia/Yekaterinburg",
    "moscow": "Europe/Moscow",
    "russian standard": "Europe/Moscow",
    "москва": "Europe/Moscow",
}


def _valid_zone(name):
    try:
        zoneinfo.ZoneInfo(name)
        return True
    except (zoneinfo.ZoneInfoNotFoundError, ValueError):
        return False


def repair_points(apps, schema_editor):
    """Починить точки, заведённые до проверки полей.

    На боевом сервере пояс был записан как «Yekaterinburg Time» (так его
    зовёт Windows), а рабочие дни — числом 2. Расчёт свободного времени
    падал на каждом запросе. Пояс угадываем по названию, иначе ставим
    пояс сети; испорченные рабочие дни — «каждый день», как и написано на
    витрине («Ежедневно»).
    """
    from django.conf import settings

    ServicePoint = apps.get_model("catalog", "ServicePoint")
    for point in ServicePoint.objects.all():
        changed = []
        if not _valid_zone(point.timezone):
            lowered = (point.timezone or "").lower()
            name = next((zone for key, zone in ALIASES.items() if key in lowered), None)
            point.timezone = name or settings.BUSINESS_TIMEZONE
            changed.append("timezone")
        days = point.workdays
        if not isinstance(days, list) or not all(
            isinstance(d, int) and not isinstance(d, bool) and 0 <= d <= 6 for d in days
        ):
            point.workdays = []
            changed.append("workdays")
        if changed:
            point.save(update_fields=changed)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_carmake_carmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepoint",
            name="timezone",
            field=models.CharField(
                choices=[
                    ("Europe/Kaliningrad", "Калининград (UTC+2)"),
                    ("Europe/Moscow", "Москва, Санкт-Петербург (UTC+3)"),
                    ("Europe/Samara", "Самара, Ижевск (UTC+4)"),
                    (
                        "Asia/Yekaterinburg",
                        "Екатеринбург, Челябинск, Тюмень, Уфа, Пермь (UTC+5)",
                    ),
                    ("Asia/Omsk", "Омск (UTC+6)"),
                    ("Asia/Novosibirsk", "Новосибирск (UTC+7)"),
                    ("Asia/Krasnoyarsk", "Красноярск, Кемерово (UTC+7)"),
                    ("Asia/Irkutsk", "Иркутск (UTC+8)"),
                    ("Asia/Yakutsk", "Якутск, Чита (UTC+9)"),
                    ("Asia/Vladivostok", "Владивосток, Хабаровск (UTC+10)"),
                    ("Asia/Magadan", "Магадан, Сахалин (UTC+11)"),
                    ("Asia/Kamchatka", "Камчатка (UTC+12)"),
                ],
                default="Europe/Moscow",
                max_length=64,
                validators=[apps.catalog.models.validate_timezone],
                verbose_name="часовой пояс",
            ),
        ),
        migrations.AlterField(
            model_name="servicepoint",
            name="workdays",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Дни недели, 0 = понедельник. Пустой список = работает всегда.",
                validators=[apps.catalog.models.validate_workdays],
                verbose_name="рабочие дни",
            ),
        ),
        migrations.RunPython(repair_points, migrations.RunPython.noop),
    ]
