# Generated by Django 5.1.4 on 2026-08-20 16:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20, verbose_name='телефон')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('push', 'Push')], default='sms', max_length=10, verbose_name='канал')),
                ('kind', models.CharField(choices=[('otp', 'Код входа'), ('booking_created', 'Запись создана'), ('booking_reminder', 'Напоминание о визите'), ('booking_cancelled_by_master', 'Отмена сервисом'), ('booking_completed', 'Работы выполнены')], max_length=32, verbose_name='тип')),
                ('text', models.TextField(verbose_name='текст')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=10, verbose_name='статус')),
                ('provider_message_id', models.CharField(blank=True, max_length=128, verbose_name='id у провайдера')),
                ('error', models.TextField(blank=True, verbose_name='ошибка')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='отправлено')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='booking.booking', verbose_name='запись')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='получатель')),
            ],
            options={
                'verbose_name': 'уведомление',
                'verbose_name_plural': 'уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', '-created_at'], name='notificatio_phone_04b825_idx'), models.Index(fields=['kind', 'status'], name='notificatio_kind_3c79bc_idx')],
            },
        ),
    ]
