# Generated by Django 5.1.15 on 2026-09-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "В очереди"),
                    ("sent", "Отправлено"),
                    ("failed", "Ошибка"),
                    ("skipped", "Не отправляли"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
                verbose_name="статус",
            ),
        ),
    ]
