# Generated by Django 5.2.17 on 2026-09-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="channel",
            field=models.CharField(
                choices=[("sms", "SMS"), ("push", "Push"), ("call", "Звонок")],
                default="sms",
                max_length=10,
                verbose_name="канал",
            ),
        ),
    ]
